# Generated by Django 6.0.7 on 2026-08-11 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilalumno_carrera_perfilalumno_generacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sae', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
