# Generated by Django 6.0.7 on 2026-08-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfilsae'),
        ('carreras', '0003_alter_area_options_alter_carrera_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilalumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='carreras.carrera'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='generacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoriaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generacion', models.PositiveSmallIntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_alumnos', to='carreras.carrera')),
                ('perfil_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='accounts.perfilalumno')),
            ],
            options={
                'ordering': ['generacion', 'id'],
                'constraints': [models.UniqueConstraint(fields=('perfil_alumno', 'carrera'), name='unique_historia_alumno_carrera')],
            },
        ),
    ]
