# Generated by Django 6.0.7 on 2026-08-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_migrar_carrera_a_historia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilalumno',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='perfilalumno',
            name='generacion',
        ),
    ]
