# Generated by Django 6.0.7 on 2026-08-16 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_perfilalumno_carrera_generacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilalumno',
            name='correos_alternos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list),
        ),
    ]
