# Generated by Django 6.0.7 on 2026-08-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_perfilalumno_correos_alternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
    ]
