services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    ports:
      - "8000:8000"

  celery-worker:
    build:
      context: ./backend
    command: celery -A config worker -l info
    env_file:
      - ./backend/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
