# Generated by Django 6.0.7 on 2026-07-30 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=5)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='asesorias.perfilasesoracademico')),
                ('materias', models.ManyToManyField(blank=True, related_name='registros_asesor', to='materias.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asesor', 'semestre'), name='unique_registro_asesor_semestre')],
            },
        ),
    ]
