# Generated by Django 6.0.7 on 2026-07-30 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0002_registroasesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('liga_virtual', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='asesorias.registroasesor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registro', 'dia_semana', 'hora_inicio'), name='unique_bloque_registro')],
            },
        ),
    ]
