# Generated by Django 6.0.7 on 2026-07-30 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilacademico_perfilalumno'),
        ('asesorias', '0003_disponibilidad'),
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('liga_virtual', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='agendada', max_length=10)),
                ('asistio', models.BooleanField(default=None, null=True)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesorias', to='accounts.perfilalumno')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesorias', to='asesorias.disponibilidad')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesorias', to='materias.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['agendada', 'realizada'])), fields=('disponibilidad', 'fecha'), name='unique_slot_disponibilidad_fecha_no_cancelada')],
            },
        ),
    ]
