# Generated by Django 6.0.7 on 2026-08-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0005_asesoria_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilasesoracademico',
            name='solicitado_por_el_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
