# Generated by Django 6.0.7 on 2026-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesorias', '0006_perfilasesoracademico_solicitado_por_el_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='motivo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
