# Generated by Django 6.0.7 on 2026-07-29 22:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('alias', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('acepta_nuevo_ingreso', models.BooleanField(default=True)),
                ('siass_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('siassypp_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('dgeci_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='carreras.area')),
            ],
        ),
    ]
