# Generated by Django 6.0.7 on 2026-08-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0002_seed_areas_carreras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre']},
        ),
    ]
