# Generated by Django 6.0.7 on 2026-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=5, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('registro_asesores_inicio', models.DateField()),
                ('registro_asesores_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'periodo académico',
                'verbose_name_plural': 'periodos académicos',
                'ordering': ['-semestre'],
            },
        ),
    ]
