# Generated by Django 6.0.7 on 2026-07-29 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0002_seed_areas_carreras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plan', models.PositiveIntegerField()),
                ('habilitada_asesorias', models.BooleanField(default=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='carreras.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=5)),
                ('se_imparte', models.BooleanField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='materias.materia')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('materia', 'semestre'), name='unique_oferta_materia_semestre')],
            },
        ),
    ]
