# Generated by Django 6.0.7 on 2026-08-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre']},
        ),
    ]
